[package]
name = "emei"
license = "GPL-3.0"
version = "0.2.0-alpha"
authors = ["Lyzh <enterindex@gmail.com>", "chuigda <icey@icey.tech>"]
edition = "2021"
description = "The EMei JIT/AOT backend framework."
repository = "https://github.com/imlyzh/emei"
readme = "README.md"

[lib]
name = "libemei"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4"

[target.'cfg(unix)'.dev-dependencies]
nix = "0.23"

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["sysinfoapi", "memoryapi"] }
